apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: asia-southeast1-docker.pkg.dev/celtic-client-473709-f9/argocd-poc-docker/hello-world-app
    newTag: v1
